# 14.1 LU분해 파이썬 실습

In [5]:
def lu_d(A):
    n = len(A)
    m = len(A[0])
    
    L = [[0]*m for i in range(0, n)]
    U = []
    
    for i in range(0, n):
        a = A[i]
        temp = 1 / a[i]
        L[i][i] = 1 / temp
        a = [element * temp for element in a]
        U.append(a)
        
        for j in range(i+1, n):
            row = A[j]
            a_temp = [element * -row[i] for element in a]
            L[j][i] = row[i]
            A[j] = [a_temp[k] + row[k] for k in range(m)]
            
    return L, U

C = [[2,-2,-2],[0,-2,2],[-1,5,2]]
L, U = lu_d(C)
print(L)
print(U)

[[2.0, 0, 0], [0, -2.0, 0], [-1, 4.0, 5.0]]
[[1.0, -1.0, -1.0], [-0.0, 1.0, -1.0], [0.0, 0.0, 1.0]]


# 14.2 LU분해 Scipy 실습

In [7]:
import numpy as np
from scipy.linalg import lu

A = np.array([[2,-2,-2],[0,-2,2],[-1,5,2]])
P, L, U = lu(A)

print(P)
print(L)
print(U)

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
[[ 1.   0.   0. ]
 [-0.5  1.   0. ]
 [ 0.  -0.5  1. ]]
[[ 2.  -2.  -2. ]
 [ 0.   4.   1. ]
 [ 0.   0.   2.5]]
