# 3.1 벡터 - 파이썬 실습

In [3]:
### 벡터의 덧셈
u = [1, 2, 3]
v = [4, 5, 6]

n = len(u)
w = []

for i in range(0, n):
    val = u[i] + v[i]
    w.append(val)
    
print(w)

[5, 7, 9]


In [4]:
### 벡터의 덧셈 함수
def v_add(u, v):
    """벡터의 덧셈"""
    n = len(u)    
    w = []
    
    for i in range(0, n):
        temp = u[i] + v[i]
        w.append(temp)
        
    return(w)

v_add([1,2,3], [4,5,6])

[5, 7, 9]

In [5]:
### 벡터의 뺄셈
u = [7, 3, 9]
v = [2, 5, 7]

n = len(u)
w = []

for i in range(0, n):
    val = u[i] - v[i]
    w.append(val)
    
print(w)

[5, -2, 2]


In [6]:
### 벡터의 뺄셈 함수
def v_subtract(u, v):
    n = len(u)
    w = []
    
    for i in range(0, n):
        temp = u[i] - v[i]
        w.append(temp)
        
    return w

v_subtract([7,3,9], [2,5,7])

[5, -2, 2]

In [10]:
### 벡터의 스칼라곱
u = [2, 4, 3]
a = 3

n = len(u)
w = []

for i in range(0, n):
    val = u[i] * a
    w.append(val)
    
print(w)

[6, 12, 9]


In [11]:
### 벡터의 스칼라곱 함수
def v_sca_mul(a, u):
    n = len(u)
    w = []
    
    for i in range(0, n):
        temp = a * u[i]
        w.append(temp)
        
    return w

v_sca_mul(3, [1,2,3])

[3, 6, 9]

In [12]:
### 벡터의 원소 곱
u = [1, 2, 4]
v = [7, 3, 2]

n = len(u)
w = []

for i in range(0, n):
    val = u[i] * v[i]
    w.append(val)
    
print(w)

[7, 6, 8]


In [13]:
### 벡터의 원소 곱 함수
def v_mul(u, v):
    n = len(u)
    w = []
    
    for i in range(0, n):
        temp = u[i] * v[i]
        w.append(temp)
    
    return w

v_mul([2,1,4], [5,6,7])

[10, 6, 28]

# 3.2 벡터- 넘파이 실습

In [14]:
import numpy as np

In [17]:
### 벡터의 덧넴
u = np.array([1,2,3])
v = np.array([4,5,6])
w = u + v

print(w)

[5 7 9]


In [18]:
### 백터의 뺄셈
w = u - v

print(w)

[-3 -3 -3]


In [19]:
### 벡터의 스칼라 곱
a = 3
w = a * u

print(w)

[3 6 9]


In [20]:
### 벡터의 원소 곱
w = u * v

print(w)

[ 4 10 18]


# 3.3 행렬 - 파이썬 실습

In [32]:
### 행렬의 덧셈
A = [[2,7], [3,4], [1,6]]
B = [[3,6], [4,6], [5,6]]

n = len(A)
p = len(A[0])
C = []

for i in range(0, n):
    row = []
    for j in range(0, p):
        temp = A[i][j] + B[i][j]
        row.append(temp)
    C.append(row)
    
print(C)

[[5, 13], [7, 10], [6, 12]]


In [39]:
### 행렬의 덧셈 함수 생성
def add(A, B):
    n = len(A)
    m = len(A[0])
    C = []
    
    for i in range(0, n):
        row = []
        for j in range(0, m):
            temp = A[i][j] + B[i][j]
            row.append(temp)
        C.append(row)
        
    return C
            
add([[1,2],[3,4]], [[5,6],[7,8]])        

[[6, 8], [10, 12]]

In [31]:
### 행렬의 뺄셈
A = [[2,7], [3,4], [1,6]]
B = [[3,6], [4,6], [5,6]]

n = len(A)
m = len(A[0])
C = [] # result

for i in range(0, n):
    row = []
    for j in range(0, m):
        temp = A[i][j] - B[i][j]
        row.append(temp)
    C.append(row)
        
print(C)


[[-1, 1], [-1, -2], [-4, 0]]


In [41]:
### 행렬의 뺄셈 함수 생성
def sub(A, B):
    n = len(A)
    m = len(A[0])
    C = []
    
    for i in range(0, n):
        row = []
        for j in range(0, m):
            temp = A[i][j] - B[i][j]
            row.append(temp)
        C.append(row)
    return C

sub([[1,2],[3,4]], [[5,6],[7,8]])   

[[-4, -4], [-4, -4]]

In [42]:
### 행렬의 스칼라곱
A = [[2,7], [3,4], [1,6]]
b = 3

n = len(A)
m = len(A[0])
C = []

for i in range(0, n):
    row = []
    for j in range(0, m):
        temp = A[i][j] * b
        row.append(temp)
    C.append(row)
    
print(C)


[[6, 21], [9, 12], [3, 18]]


In [43]:
### 행렬의 스칼라곱 함수 생성
def times(A, b):
    n = len(A)
    m = len(A[0])
    C = []
    
    for i in range(0, n):
        row = []
        for j in range(0, m):
            temp = A[i][j] * b
            row.append(temp)
        C.append(row)
        
    return C

times([[1,2],[5,6]], 3)

[[3, 6], [15, 18]]

In [44]:
### 행렬의 곱
A = [[1,2],[2,7],[3,2]] # n by m
B = [[3,2,1],[2,4,6]] # m by l

n = len(A)
m = len(A[0])
l = len(B[0])
C = [] # result

for i in range(0, n):
    row = []
    for j in range(0, m):
        temp = 0
        for k in range(0, l):
            temp += A[i][j] * B[j][k]
        row.append(temp)
    C.append(row)
    
print(C)

[[6, 24], [12, 84], [18, 24]]


In [3]:
### 행렬의 곱 함수 생성
def product(A, B): # A for n by m / B for m by l
    n = len(A)
    m = len(A[0])
    l = len(B[0])
    
    C = [] # result
    
    for i in range(0, n):
        row = []
        for j in range(0, l):
            temp = 0
            for k in range(0, m):
                temp += A[i][k] * B[k][j]
            row.append(temp)
        C.append(row)
        
    return C

product([[1,0],[2,4]], [[-1,2],[0,7]])

[[-1, 2], [-2, 32]]

# 3.4 행렬 넘파이 실습

In [51]:
### 행렬의 덧셈
import numpy as np
#A = np.array[[2,7],[3,2],[5,5]])
#B = np.array[[3,0],[3,4],[3,3]]

A = np.array([[2,3],[4,5]])
B = np.array([[6,2],[1,3]])

C = A + B
print (C)

[[8 5]
 [5 8]]


In [53]:
### 행렬의 원소곱
A = np.array([[2,3],[4,5]])
B = np.array([[6,2],[1,3]])
C = np.multiply(A, B)

print(C)

[[12  6]
 [ 4 15]]


In [54]:
### 행렬의 곱
A = np.array([[2,3],[4,5]])
B = np.array([[6,2],[1,3]])
C = np.matmul(A, B)

print(C)


[[15 13]
 [29 23]]
