# 4.1 전치 행렬 파이썬 실습

In [3]:
### 전치 행렬
A = [[1,2],[3,4],[5,6]] # for n by m matrix

n = len(A)
m = len(A[0])
At = [] # result

for i in range(0, m):
    row = []
    for j in range(0, n):
        temp = A[j][i]
        row.append(temp)
    At.append(row)
    
print(At)

[[1, 3, 5], [2, 4, 6]]


In [5]:
### 전치 행렬 생성 함수
def tp(A):
    n = len(A)
    m = len(A[0])
    At = [] # result
    
    for i in range(0, m):
        row = []
        for j in range(0, n):
            temp = A[j][i]
            row.append(temp)
        At.append(row)    
    
    return At

tp([[1,2,3],[4,5,6]])

[[1, 4], [2, 5], [3, 6]]

# 4.2 전치 행렬 넘파이 실습

In [8]:
### 전치 행렬
import numpy as np

A = np.array([[1,2,3],[4,5,6]])
At = np.transpose(A)

print(At)

[[1 4]
 [2 5]
 [3 6]]


# 4.3 대각 행렬 파이썬 실습

In [9]:
### 대각 행렬
A = [[1,2,3],[4,5,6],[7,8,9]]

n = len(A)
D = [] # result

for i in range(0, n):
    row = []
    for j in range(0, n):
        if i==j:
            row.append(A[i][j])
        else:
            row.append(0)
    D.append(row)

print(D)

[[1, 0, 0], [0, 5, 0], [0, 0, 9]]


In [12]:
### 대각 행렬 생성 함수
def diag(A):
    """대각 행렬 생성 함수"""
    n = len(A) # for n by n matrix
    D = [] # result matrix
    
    for i in range(0, n):
        row = []
        for j in range(0, n):
            if i==j:
                row.append(A[i][j])
            else:
                row.append(0)
        D.append(row)        
        
    return D

diag([[1,2,3],[4,5,6],[7,8,9]])

[[1, 0, 0], [0, 5, 0], [0, 0, 9]]

In [13]:
### 대각 원소 추출
A = [[1,2,3],[4,5,6],[7,8,9]]

n = len(A)
ele = []
for i in range(0, n):
    ele.append(A[i][i])

print(ele)

[1, 5, 9]


In [14]:
### 대각 원소 추출 함수
def diag_ele(A):
    """대각 원소 추출 함수"""
    n = len(A)
    ele = []
    for i in range(0, n):
        ele.append(A[i][i])
        
    return(ele)

diag_ele([[1,2,3],[4,5,6],[7,8,9]])

[1, 5, 9]

In [15]:
### 대각 원소를 대각 행렬로 변환
ele = [1, 9, 5]

n = len(ele)
D = [] # return matrix

for i in range(0, n):
    row = []
    for j in range(0, n):
        if i==j:
            row.append(ele[i])
        else:
            row.append(0)
    D.append(row)
    
print(D)

[[1, 0, 0], [0, 9, 0], [0, 0, 5]]


In [17]:
### 대각 원소를 대각 행렬로 변환하는 함수
def ele_diag(ele):
    n = len(ele)
    D = [] # return matrix
    
    for i in range(0,n):
        row = []
        for j in range(0, n):
            if i==j:
                row.append(ele[i])
            else:
                row.append(0)
        D.append(row)
    return D

ele_diag([1,2,3])

[[1, 0, 0], [0, 2, 0], [0, 0, 3]]

# 4.4 대각 행렬 넘파이 실습

In [21]:
### 대각 원소 추출
### 대각화 행렬
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
ele = np.diag(A)

print(ele)
D = np.diag(ele)
print(D)

[1 5 9]
[[1 0 0]
 [0 5 0]
 [0 0 9]]


# 4.5 단위 행렬 파이썬 실습

In [22]:
### 단위 행렬
n = 5

I = [] # result matrix

for i in range(0, n):
    row = []
    for j in range(0, n):
        if i==j:
            row.append(1)
        else:
            row.append(0)
    I.append(row)
    
print(I)

[[1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 1]]


In [23]:
### 단위 행렬 생성 함수
def iden(n):
    """n by n의 단위 행렬 생성 함수"""
    I = [] # result matrix
    
    for i in range(0, n):
        row = []
        for j in range(0, n):
            if i==j:
                row.append(1)
            else:
                row.append(0)
        I.append(row)
    return I

iden(7)

[[1, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 1]]

# 4.6 단위 행렬 넘파이 실습

In [24]:
I = np.identity(6)
print(I)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


# 4.7 영행렬 파이썬 실습

In [25]:
### 영행렬
n = 4
Z = [] # result matrix

for i in range(0, n):
    row = []
    for j in range(0, n):
        row.append(0)
    Z.append(row)
    
print(Z)

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]


In [27]:
### 영행렬 생성 함수
def zero(n):
    """n by n 영행렬 생성 함수"""
    Z = [] # result matrix
    
    for i in range(0, n):
        row = []
        for j in range(0, n):
            row.append(0)
        Z.append(row)
    return Z

zero(3)
            

[[0, 0, 0], [0, 0, 0], [0, 0, 0]]

# 4.8 영행렬 넘파이 실습

In [28]:
Z = np.zeros((3,2))
print(Z)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


# 4.9 삼각 행렬 파이썬 실습

In [30]:
### 상삼각행렬(utm)

A = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]

n = len(A)
m = len(A[0])
utm = [] # result matrix

for i in range(0, n):
    row = []
    for j in range(0, m):
        if i>j:
            row.append(0)
        else:
            row.append(A[i][j])
    utm.append(row)
    
print(utm)

[[1, 2, 3], [0, 5, 6], [0, 0, 9], [0, 0, 0]]


In [31]:
### 상삼각행렬 생성 함수

def utm(A):
    """상삼각행렬 생성 함수"""

    n = len(A)
    m = len(A[0])
    ut = [] # result matrix
    for i in range (0, n):
        row = []
        for j in range(0, m):
            if i > j:
                row.append(0)
            else:
                row.append(A[i][j])
        ut.append(row)
    return ut

utm([[1,2,3],[4,5,6],[7,8,9]])
        



[[1, 2, 3], [0, 5, 6], [0, 0, 9]]

In [33]:
### 하상각행렬(ltm)
A = [[1,2,3],[4,5,6],[7,8,9]]

n = len(A)
m = len(A[0])
ltm = [] # result matrix

for i in range(0, n):
    row = []
    for j in range(0, m):
        if i > j:
            row.append(A[i][j])
        else:
            row.append(0)
    ltm.append(row)
    
print(ltm)

[[0, 0, 0], [4, 0, 0], [7, 8, 0]]


In [34]:
### 하상각행렬 생성 함수

def ltm(A):
    n = len(A)
    m = len(A[0])
    lt = [] # result matrix
    
    for i in range(0, n):
        row = []
        for j in range(0, m):
            if i > j:
                row.append(A[i][j])
            else:
                row.append(0)
        lt.append(row)
        
    return lt

ltm([[1,2,3],[4,5,6],[7,8,9]])

[[0, 0, 0], [4, 0, 0], [7, 8, 0]]

# 4.10 삼각행렬 넘파이 실습

In [38]:
### 상삼각행렬
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
Au = np.triu(A)

print(Au)

[[1 2 3]
 [0 5 6]
 [0 0 9]]


In [39]:
### 하삼각행렬
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
Al = np.tril(A)

print(Al)

[[1 0 0]
 [4 5 0]
 [7 8 9]]


# 4.11 토플리츠 행렬 넘파이 실습

In [42]:
### 토플리츠 행렬
a = [1, 0, -2, -4]
b = [1, 3, 5, 7, 9]

n1 = len(a)
n2 = len(b)
A = [] # result matrix

for i in range(0, n1):
    row = []
    for j in range(0, n2):
        if i > j:
            row.append(a[i-j])
        else:
            row.append(b[i-j])
    A.append(row)
    
print(A)


[[1, 9, 7, 5, 3], [0, 1, 9, 7, 5], [-2, 0, 1, 9, 7], [-4, -2, 0, 1, 9]]


In [43]:
### 토플리츠 행렬 생성 함수
def toep(a, b):
    """토플리츠 행렬 변환 함수"""
    n1 = len(a)
    n2 = len(b)
    A = [] # result matrix
    
    for i in range(0, n1):
        row = []
        for j in range(0, n2):
            if i > j:
                row.append(a[i-j])
            else:
                row.append(b[i-j])
        A.append(row)
    return A

toep([1,0,-2,4],[1,3,5,7,9])
    

[[1, 9, 7, 5, 3], [0, 1, 9, 7, 5], [-2, 0, 1, 9, 7], [4, -2, 0, 1, 9]]

# 4.12 토플리츠 행렬 사이파이 실습

In [48]:
### 토플리츠 행렬 생성
from scipy.linalg import toeplitz
A = toeplitz([1,0,-2,4],[1,3,5,6,8])
print(A)

[[ 1  3  5  6  8]
 [ 0  1  3  5  6]
 [-2  0  1  3  5]
 [ 4 -2  0  1  3]]


# 4.13 이중 대각 행렬 파이썬 실습

In [49]:
### 상방 이중 대각 행렬(ubdm)
A = [[1,2,1,3],[5,3,4,1],[2,1,7,9],[2,8,1,3]]

n = len(A)
m = len(A[0])
ubdm = [] # result matrix

for i in range(0, n):
    row = []
    for j in range(0, m):
        if i > j or j-i > 1 :
            row.append(0)
        else:
            row.append(A[i][j])
    ubdm.append(row)        
    
print(ubdm)

[[1, 2, 0, 0], [0, 3, 4, 0], [0, 0, 7, 9], [0, 0, 0, 3]]


In [51]:
### 상방 이중 대각 행렬 생성 함수
def ubdm(A):
    n = len(A)
    m = len(A[0])
    ubd = [] # result matrix
    
    for i in range(0, n):
        row = []
        for j in range(0, m):
            if i > j or j > i +1:
                row.append(0)
            else:
                row.append(A[i][j])
        ubd.append(row)
    return ubd

ubdm([[1,2,3],[4,5,6],[7,8,9]])

[[1, 2, 0], [0, 5, 6], [0, 0, 9]]

In [62]:
### 하방 이중 대각 행렬 (lbdm)
A = [[1,2,3],[4,5,6],[7,8,9]]

n = len(A)
m = len(A[0])
lbdm = [] # result matrix

for i in range(0, n):
    row = []
    for j in range(0, m):
        if i < j or i > j + 1:
            row.append(0)
        else:
            row.append(A[i][j])
    lbdm.append(row)
    
print(lbdm)

[[1, 0, 0], [4, 5, 0], [0, 8, 9]]


In [64]:
### 하방 이중 대각 행렬 생성 함수
def lbdm(A):
    n = len(A)
    m = len(A[0])
    lbd = [] # result matrix
    
    for i in range(0, n):
        row = []
        for j in range(0, m):
            if i < j or i > j+1 : 
                row.append(0)
            else:
                row.append(A[i][j])
        lbd.append(row)
        
    return lbd

lbdm([[1,2,3],[4,5,6],[7,8,9]])

[[1, 0, 0], [4, 5, 0], [0, 8, 9]]

# 4.14 이중대각행렬 넘파이 실습

In [72]:
### ubdm
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
diag_ele = np.diag(A) # 대각성분 추출
udiag_ele = np.diag(A, k=1) # k=1 성분 추출

ubdm = np.diag(diag_ele) + np.diag(udiag_ele, k=1)
print(ubdm)

[[1 2 0]
 [0 5 6]
 [0 0 9]]


In [75]:
### lbmd
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
diag_ele = np.diag(A)
ldiag_ele = np.diag(A, k=-1)

lbdm = np.diag(diag_ele) + np.diag(ldiag_ele, k=-1)
print(lbdm)

[[1 0 0]
 [4 5 0]
 [0 8 9]]


# 4.15 하우스홀더 행렬 파이썬 실습

_H = I - 2(dp/cp)_

In [124]:
v = [1, 0, 2, 3]
N = len(v)

### dp 함수 생성
def dp(a, b):
    """vector dot product"""
    n = len(a)
    d = 0 # result from dp
    for i in range(0, n):
        d += a[i]*b[i]
    return d

### cp 함수 생성
def cp(a, b):
    """vector outer product"""
    n = len(a)
    c = [] # result from cp
    for i in range(0, n):
        row = []
        for j in range(0, n):
            temp = a[i]*b[j]
            row.append(temp)                
        c.append(row)
    return c
        
### 단위 행렬 생성
I = []
for i in range(0, N):
    row = []
    for j in range(0, N):
        if i==j:
            row.append(1)
        else:
            row.append(0)
    I.append(row)

### 행렬의 뺄셈 정의
def sub(A, B):
    """vector substraction"""
    n = len(A)
    m = len(A[0])
    C = [] # result from sub
    for i in range(0, n):
        row = []
        for j in range(0, m):
            temp = A[i][j] - B[i][j]
            row.append(temp)
        C.append(row)
    return C

### 행렬의 스칼라곱정의
def times(A, b):
    n = len(A)
    C = [] # result
    for i in range(0, n):
        row = []
        for j in range(0, n):
            temp = A[i][j] * b
            row.append(temp)
        C.append(row)
    return C

### householder 계산
V = times(cp(v,v),2*(1/dp(v,v)))
sub(I,V)   


[[0.8571428571428572, 0.0, -0.2857142857142857, -0.42857142857142855],
 [0.0, 1.0, 0.0, 0.0],
 [-0.2857142857142857, 0.0, 0.4285714285714286, -0.8571428571428571],
 [-0.42857142857142855, 0.0, -0.8571428571428571, -0.2857142857142856]]

# 4.16 하우스홀더 행렬 넘파이 실습

In [127]:
def hh(v):
    n = len(v)
    cp = np.outer(v, v)
    dp = np.inner(v, v)
    I = np.identity(n)
    return I - (2/dp)*cp

hh([1,0,2,3])

array([[ 0.85714286,  0.        , -0.28571429, -0.42857143],
       [ 0.        ,  1.        ,  0.        ,  0.        ],
       [-0.28571429,  0.        ,  0.42857143, -0.85714286],
       [-0.42857143,  0.        , -0.85714286, -0.28571429]])